[versions]
agp = "8.11.1"
annotation = "1.9.1"
api = "82"
dexkit = "2.0.6"
dexkitcache = "v.0.7"
gson = "2.13.1"
hooktool = "v.2.1.6"
mmkv = "2.2.2"
superlyricapi = "2.1"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
api = { module = "de.robv.android.xposed:api", version.ref = "api" }
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
dexkitcache = { module = "com.github.HChenX:DexkitCache", version.ref = "dexkitcache" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hooktool = { group = "com.github.HChenX", name = "HookTool", version.ref = "hooktool" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
superlyricapi = { module = "com.github.HChenX:SuperLyricApi", version.ref = "superlyricapi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

