name: Android CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "*.md"
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.13'

      - name: Create Sign
        run: |
          echo keyAlias=${{ secrets.ALIAS }} >> local.properties
          echo keyStorePassword=${{ secrets.KEY_STORE_PASSWORD }} >> local.properties
          echo keyAliasPassword=${{ secrets.KEY_STORE_PASSWORD }} >> local.properties
          echo keyStoreFile=key.jks >> local.properties
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > key.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Release Apk
        uses: actions/upload-artifact@v4
        with:
          name: SuperLyric_release
          path: ./app/build/outputs/apk/release

      - name: Upload Debug Apk
        uses: actions/upload-artifact@v4
        with:
          name: SuperLyric_debug
          path: ./app/build/outputs/apk/debug

      - name: Get App Version
        id: version
        run: |
          VERSION_NAME=$(grep versionName app/build/outputs/apk/release/output-metadata.json | head -1 | cut -d ':' -f2 | cut -d \" -f2)
          echo "VERSION_NAME=$VERSION_NAME"
          echo "version=$VERSION_NAME" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: SuperLyric ${{ steps.version.outputs.version }}
          body: |
            ğŸ‰ æ–°ç‰ˆæœ¬å‘å¸ƒï¼

            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          files: ./app/build/outputs/apk/**/*.apk

